spring.datasource.url=${DBDATABASE}
spring.datasource.username=${RDS_USER}
spring.datasource.password=${RDS_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

eduessence.streaming.provider=${STREAMING_PROVIDER:AWS_IVS}
